plan_story_arc:
  description: |
    Develop a high-level story arc for the entire book, including major plot points, character arcs, 
    and turning points. The story should follow the genre-specific structure and conventions.
    Define:
    - Overall story structure
    - Major plot points
    - Character arcs
    - Key themes
    - Narrative style and tone
    Store the story arc in the project notes.

create_chapter_outlines:
  description: |
    Create detailed outlines for each chapter based on the story arc.
    For each chapter include:
    - Chapter title and number
    - Scene list with descriptions
    - Key events and developments
    - Character appearances and development
    - Setting details
    - Themes and symbolism
    - Important items or props
    Consider pacing, tension, and narrative flow when creating the outlines.
    Each chapter outline should advance both plot and character development.
    Store each chapter outline in the project notes.